---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch.yaml

images:
  - name: docker-react-playground
    newName: docker-react-playground
    newTag: latest

replicas:
  - name: docker-react-playground
    count: 1
