apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-react-playground
spec:
  template:
    spec:
      containers:
        - name: docker-react-playground
          image: docker-react-playground
          env:
            - name: REACT_APP_ENV
              value: dev
