apiVersion: v1
kind: Service
metadata:
  name: docker-react-playground
spec:
  selector:
    app: docker-react-playground
  ports:
    - name: http
      port: 80
      targetPort: 3000
  # type: LoadBalancer
